export const GET_RECIPE_BY_ID = 'GET_RECIPE_BY_ID';
export const GET_ALL_RECIPES = 'GET_ALL_RECIPES';
export const SET_RATING_BY_ID = 'SET_RATING_BY_ID';
export const ADD_NEW_RECIPE = 'ADD_NEW_RECIPE';
export const ITEMS_LOADING = 'ITEMS_LOADING';
